//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TZInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TZInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;rowse.
        /// </summary>
        internal static string LABEL_TEXT_CMDBROWSEFORFILE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_CMDBROWSEFORFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go.
        /// </summary>
        internal static string LABEL_TEXT_CMDGO {
            get {
                return ResourceManager.GetString("LABEL_TEXT_CMDGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;BaseUTCoffset.
        /// </summary>
        internal static string LABEL_TEXT_LBLBASEUTCOFFSET {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLBASEUTCOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day&amp;lightName.
        /// </summary>
        internal static string LABEL_TEXT_LBLDAYLIGHTNAME {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLDAYLIGHTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;DisplayName.
        /// </summary>
        internal static string LABEL_TEXT_LBLDISPLAYNAME {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLDISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output File Name.
        /// </summary>
        internal static string LABEL_TEXT_LBLOUTPUTFILE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLOUTPUTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;StandardName.
        /// </summary>
        internal static string LABEL_TEXT_LBLSTANDARDNAME {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLSTANDARDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;upports DST.
        /// </summary>
        internal static string LABEL_TEXT_LBLSUPPORTSDST {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLSUPPORTSDST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;Time Zone.
        /// </summary>
        internal static string LABEL_TEXT_LBLTIMEZONE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_LBLTIMEZONE", resourceCulture);
            }
        }
    }
}
