//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZoneLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeZoneLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} cannot be found in assembly {1}..
        /// </summary>
        internal static string ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading a file from resources embedded in the assembly.{3}Internal Name = {0}{3}File Length (bytes) = {1}{3}Bytes successfully read = {2}.
        /// </summary>
        internal static string ERRMSG_EMBEDDED_RESOURCE_READ_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA ERROR: The input file is corrupt. DateTime.TryParse cannot parse string {0} found in record {1} of {2}..
        /// </summary>
        internal static string ERRMSG_INVALID_DATE_STRING {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_DATE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}The specified output format, {0}, is invalid, and will be ignored.{2}    The default value, {1}, will be used.{2}.
        /// </summary>
        internal static string ERRMSG_INVALID_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_OUTPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified time zone ID, {0}, is invalid for this machine..
        /// </summary>
        internal static string ERRMSG_INVALID_TIME_ZONE_ID {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_TIME_ZONE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the time zone for which to list the adjustments..
        /// </summary>
        internal static string ERRMSG_MISSING_TIME_ZONE_ID {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_TIME_ZONE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception has occurred..
        /// </summary>
        internal static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task completed successfully.
        /// </summary>
        internal static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified task ID is invalid..
        /// </summary>
        internal static string ERRMSG_TASK_SPECIFIER_INVALID {
            get {
                return ResourceManager.GetString("ERRMSG_TASK_SPECIFIER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified test case file cannot be found. See the user scoped EdgeCaseInputFileName setting..
        /// </summary>
        internal static string ERRMSG_TEST_CASE_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_TEST_CASE_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the test case file is missing. See the user scoped EdgeCaseInputFileName setting..
        /// </summary>
        internal static string ERRMSG_TEST_CASE_FILENAME_IS_MISSING {
            get {
                return ResourceManager.GetString("ERRMSG_TEST_CASE_FILENAME_IS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is not yet implemented..
        /// </summary>
        internal static string ERRMSG_UNIMPLEMENTED_TASK {
            get {
                return ResourceManager.GetString("ERRMSG_UNIMPLEMENTED_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string METHOD_NAME_IS_MAIN {
            get {
                return ResourceManager.GetString("METHOD_NAME_IS_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Output: {0}{1}.
        /// </summary>
        internal static string MSG_OUTPUT_BEGIN {
            get {
                return ResourceManager.GetString("MSG_OUTPUT_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0} completed.{1}.
        /// </summary>
        internal static string MSG_OUTPUT_DONE {
            get {
                return ResourceManager.GetString("MSG_OUTPUT_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Task to Perform: {0}{1}.
        /// </summary>
        internal static string MSG_SELECTED_TASK {
            get {
                return ResourceManager.GetString("MSG_SELECTED_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Task {0} completed{1}.
        /// </summary>
        internal static string MSG_TASK_DONE {
            get {
                return ResourceManager.GetString("MSG_TASK_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Test Case {0}: Input Time  = {1} {2}{5}                 Output Time = {3} {4}{5}.
        /// </summary>
        internal static string MSG_TZ_CONVERSION {
            get {
                return ResourceManager.GetString("MSG_TZ_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLength computation is not yet implemented for this field..
        /// </summary>
        internal static string MSG_UNIMPLEMENTED {
            get {
                return ResourceManager.GetString("MSG_UNIMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaylightAbbr.
        /// </summary>
        internal static string RPT_LBL_DA {
            get {
                return ResourceManager.GetString("RPT_LBL_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        internal static string RPT_LBL_DN {
            get {
                return ResourceManager.GetString("RPT_LBL_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaylightName.
        /// </summary>
        internal static string RPT_LBL_DT {
            get {
                return ResourceManager.GetString("RPT_LBL_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string RPT_LBL_ID {
            get {
                return ResourceManager.GetString("RPT_LBL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardAbbr.
        /// </summary>
        internal static string RPT_LBL_SA {
            get {
                return ResourceManager.GetString("RPT_LBL_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportsDST.
        /// </summary>
        internal static string RPT_LBL_SD {
            get {
                return ResourceManager.GetString("RPT_LBL_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardName.
        /// </summary>
        internal static string RPT_LBL_SN {
            get {
                return ResourceManager.GetString("RPT_LBL_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUTCoffset.
        /// </summary>
        internal static string RPT_LBL_UO {
            get {
                return ResourceManager.GetString("RPT_LBL_UO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelsForTasks.TXT.
        /// </summary>
        internal static string TASK_LABEL_FILENAME {
            get {
                return ResourceManager.GetString("TASK_LABEL_FILENAME", resourceCulture);
            }
        }
    }
}
